# Generated by Django 3.2.4 on 2021-06-21 17:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='passenger',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(help_text='passenger name here', max_length=60)),
                ('p_age', models.IntegerField(help_text='Give original age,no fake ages allowed')),
                ('p_gender', models.CharField(blank=True, max_length=10)),
                ('p_phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('ticket_id', models.CharField(help_text='This should be admin generated', max_length=32, primary_key=True, serialize=False)),
                ('ticket_source', models.CharField(blank=True, help_text='Departure Station ', max_length=32)),
                ('ticket_dest', models.CharField(blank=True, help_text='Arrival Station ', max_length=32)),
                ('ticket_class', models.CharField(help_text='Seat Quality', max_length=12)),
                ('ticket_seat_no', models.CharField(max_length=12)),
                ('ticket_fare', models.IntegerField()),
                ('ticket_of_passenger', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='train.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(help_text='Put Genuine Email Here', max_length=60)),
                ('user_password', models.CharField(help_text='need to implement sha-256', max_length=256, validators=[django.core.validators.RegexValidator(code='nomatch', message='min length 6 , At least one upper case, At least one lower case & At least one digit', regex='^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9]).{6,}$')])),
                ('user_signin_date', models.DateTimeField()),
                ('user_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='transection',
            fields=[
                ('account_no', models.CharField(help_text='type account number or Bkash phone Number', max_length=60, primary_key=True, serialize=False)),
                ('account_holder_name', models.CharField(blank=True, max_length=60)),
                ('cvv', models.CharField(blank=True, max_length=3)),
                ('expiry_date', models.DateField(blank=True)),
                ('transaction_pin', models.CharField(help_text='Bkash transaction or Bank slip number', max_length=32)),
                ('bill_cleared', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, unique=True, upload_to='')),
                ('transaction_for_ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='train.ticket')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.user')),
            ],
        ),
        migrations.AddField(
            model_name='passenger',
            name='p_transaction_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='train.transection'),
        ),
    ]
