# Generated by Django 3.2.4 on 2021-06-20 04:55

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(help_text='AutoField is used', primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=32)),
                ('user_age', models.IntegerField(max_length=3)),
                ('user_email', models.EmailField(help_text='EmailField is used', max_length=50)),
                ('user_phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('user_otp', models.SlugField(blank=True, help_text='SlugField is used', max_length=200, unique=True)),
                ('user_sign_in_time', models.DateTimeField()),
                ('user_status', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
