# Generated by Django 3.2.4 on 2021-06-29 17:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='passenger',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(help_text='passenger name here', max_length=60)),
                ('p_age', models.IntegerField(help_text='Give original age,no fake ages allowed')),
                ('p_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Prefer not to say', 'Prefer not to say')], default='male', max_length=64)),
                ('p_phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
            ],
            options={
                'db_table': 'passenger',
                'ordering': ['p_id'],
            },
        ),
        migrations.CreateModel(
            name='route',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_stoppages', models.CharField(help_text='comma separated stoppages name', max_length=256, null=True)),
                ('r_arrival_date', models.DateField(blank=True, null=True)),
                ('r_arrival_time', models.TimeField(blank=True, null=True)),
                ('r_departure_date', models.DateField(blank=True, null=True)),
                ('r_departure_time', models.TimeField(blank=True, null=True)),
                ('r_arrival_station', models.CharField(help_text='From ticket it should be auto generated', max_length=32, null=True)),
                ('r_departure_station', models.CharField(help_text='From ticket it should be auto generated', max_length=32, null=True)),
                ('r_line_no', models.SmallIntegerField(help_text="This is station's route line number", null=True)),
            ],
            options={
                'db_table': 'route',
                'ordering': ['r_id'],
            },
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('ticket_id', models.CharField(help_text='This should be admin generated', max_length=32, primary_key=True, serialize=False)),
                ('ticket_source', models.CharField(blank=True, help_text='Departure Station ', max_length=32)),
                ('ticket_dest', models.CharField(blank=True, help_text='Arrival Station ', max_length=32)),
                ('ticket_class', models.CharField(help_text='Seat Quality', max_length=64)),
                ('ticket_seat_no', models.CharField(max_length=32)),
                ('ticket_fare', models.IntegerField()),
                ('ticket_of_passenger', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='train.passenger')),
            ],
            options={
                'db_table': 'ticket',
                'ordering': ['-ticket_id'],
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(help_text='Put Genuine Email Here', max_length=60)),
                ('user_password', models.CharField(help_text='need to implement sha-256', max_length=256, validators=[django.core.validators.RegexValidator(code='nomatch', message='min length 6 , At least one upper case, At least one lower case & At least one digit', regex='^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9]).{6,}$')])),
                ('user_signin_date', models.DateTimeField()),
                ('user_status', models.CharField(choices=[('Guest', 'Guest'), ('Passenger', 'Passenger'), ('Manager', 'Manager'), ('Clerk', 'Clerk'), ('Admin', 'Admin')], default='Guest', help_text='Choose status', max_length=32)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='transection',
            fields=[
                ('payment_gateway', models.CharField(choices=[('Bkash', 'Bkash'), ('Nogod', 'Nogod'), ('Rocket', 'Rocket'), ('Debi Card', 'Debit Card'), ('Credit Card', 'Credit Card')], default='Nogod', help_text='Choose your favourable payment gateway', max_length=32)),
                ('account_no', models.CharField(help_text='type account number or Bkash phone Number', max_length=60, primary_key=True, serialize=False)),
                ('account_holder_name', models.CharField(blank=True, max_length=60, null=True)),
                ('cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('transaction_pin', models.CharField(help_text='Bkash transaction or Bank slip number', max_length=32)),
                ('bill_cleared', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, null=True, unique=True, upload_to='')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transections', to='train.ticket')),
            ],
            options={
                'db_table': 'transection',
                'ordering': ['transaction_id'],
            },
        ),
        migrations.CreateModel(
            name='train_info',
            fields=[
                ('train_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('train_name', models.CharField(help_text='Give exclusive train name here', max_length=64)),
                ('train_service', models.CharField(max_length=256)),
                ('train_weekened', models.CharField(blank=True, max_length=12)),
                ('train_info', models.TextField(blank=True)),
                ('train_route', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='train_infos', to='train.route')),
            ],
            options={
                'db_table': 'train_info',
                'ordering': ['train_id'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_train',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='train.train_info'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='p_transaction_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='train.user'),
        ),
    ]
