# Generated by Django 3.2.4 on 2021-06-21 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passenger',
            options={'ordering': ['p_id']},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['r_id']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['ticket_id']},
        ),
        migrations.AlterModelOptions(
            name='train_info',
            options={'ordering': ['train_id']},
        ),
        migrations.AlterModelOptions(
            name='transection',
            options={'ordering': ['transaction_id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['user_id']},
        ),
    ]
