# Generated by Django 3.2.4 on 2021-07-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-ticket_issue_date']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='p_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Prefer not to say', 'Prefer not to say')], default='Male', max_length=64),
        ),
        migrations.AlterField(
            model_name='transection',
            name='payment_gateway',
            field=models.CharField(choices=[('Mobile Banking', 'Mobile Banking'), ('Credit/Debit Card', 'Credit/Debit Card')], default='Mobile Banking', help_text='Choose your favourable payment gateway', max_length=32),
        ),
    ]
