# Generated by Django 3.2.4 on 2021-06-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='passenger',
            table='passenger',
        ),
        migrations.AlterModelTable(
            name='route',
            table='route',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
        migrations.AlterModelTable(
            name='train_info',
            table='train_info',
        ),
        migrations.AlterModelTable(
            name='transection',
            table='transaction',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
