# Generated by Django 3.2.4 on 2021-06-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_auto_20210622_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_info',
            name='train_weekened',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
