# Generated by Django 3.2.4 on 2021-07-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_auto_20210703_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transection',
            name='qr_code',
        ),
    ]
