# Generated by Django 3.2.4 on 2021-06-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_alter_train_info_train_weekened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='p_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
