# Generated by Django 3.2.4 on 2021-07-03 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_remove_transection_qr_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passenger',
            options={'ordering': ['p_name']},
        ),
    ]
