# Generated by Django 3.2.4 on 2021-07-03 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_alter_passenger_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_of_passenger',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='train.passenger'),
        ),
    ]
