# Generated by Django 3.2.4 on 2021-06-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_alter_passenger_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='p_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Prefer not to say', 'Prefer not to say')], default='Prefer not to say', max_length=32),
        ),
    ]
