# Generated by Django 3.2.4 on 2021-07-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0005_alter_ticket_ticket_of_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='transection',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='static/qrcode'),
        ),
    ]
