# Generated by Django 3.2.4 on 2021-06-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0005_alter_passenger_p_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-ticket_id']},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('Guest', 'Guest'), ('Passenger', 'Passenger'), ('Manager', 'Manager'), ('Clerk', 'Clerk'), ('Admin', 'Admin')], default='Guest', help_text='Choose status', max_length=32),
        ),
    ]
