# Generated by Django 3.2.4 on 2021-06-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0006_auto_20210623_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='transection',
            name='payment_gateway',
            field=models.CharField(choices=[('Bkash', 'Bkash'), ('Nogod', 'Nogod'), ('Rocket', 'Rocket'), ('Visa Card', 'Visa Card'), ('Master Card', 'Master Card')], default='Nogod', help_text='Choose your favourable payment gateway', max_length=32),
        ),
        migrations.AlterField(
            model_name='route',
            name='r_line_no',
            field=models.IntegerField(help_text="This is station's route line number"),
        ),
    ]
