# Generated by Django 3.2.4 on 2021-06-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0007_auto_20210623_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='r_line_no',
            field=models.SmallIntegerField(help_text="This is station's route line number"),
        ),
    ]
